# Generated by Django 4.2.27 on 2026-02-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('revision', 'Needs Revision')], default='not_started', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Completion percentage 0-100')),
                ('key_points', models.TextField(blank=True, default='', help_text='Key takeaways or important points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='vault.chapter')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
