# Generated by Django 4.2.27 on 2026-02-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within chapter'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('UPLOAD', 'Uploaded File'), ('YOUTUBE', 'YouTube Link')], default='UPLOAD', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_id',
            field=models.CharField(blank=True, help_text='Google Drive File ID for uploaded videos', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='folder', help_text="Icon identifier (e.g., 'folder', 'book', 'code')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within vault')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='videos.vault')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('vault', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='videos.subject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('subject', 'title')},
            },
        ),
        migrations.AddField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter this video belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.chapter'),
        ),
    ]
