# Generated by Django 4.2.27 on 2026-02-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        ('videos', '0002_video_file_size_video_mime_type_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vault.category'),
        ),
        migrations.AddField(
            model_name='video',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Category/Organization path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vault.organization'),
        ),
    ]
