# Generated by Django 4.2.27 on 2026-02-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_category_video_folder_path_video_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.IntegerField(default=0, help_text='Processing progress percentage 0-100'),
        ),
    ]
