# Generated by Django 4.2.27 on 2026-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_duration_video_thumbnail_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive Folder ID containing video assets', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.CharField(blank=True, help_text='Google Drive File ID for preview clip', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='Google Drive File ID for thumbnail', max_length=255, null=True),
        ),
    ]
