# Generated by Django 4.2.27 on 2026-02-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_chapter'),
        ('videos', '0006_drive_storage_for_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vault.chapter'),
        ),
    ]
