# Generated by Django 4.2.27 on 2026-02-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0007_video_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_id', models.CharField(blank=True, help_text='Google Drive File ID', max_length=255, null=True)),
                ('folder_path', models.CharField(blank=True, help_text='Category/Organization path on Drive', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Serialised annotation data (highlights, notes, drawings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.chapter')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
