# Generated by Django 4.2.27 on 2026-02-10 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0008_add_document_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(help_text='1-based page number')),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('note', 'Sticky Note'), ('drawing', 'Freehand Drawing'), ('text', 'Text'), ('shape', 'Shape')], max_length=20)),
                ('data', models.JSONField(help_text='Annotation data (position, text, color, paths, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_id', models.CharField(blank=True, help_text='Google Drive File ID', max_length=255, null=True)),
                ('drive_folder_id', models.CharField(blank=True, help_text='Google Drive Folder ID', max_length=255, null=True)),
                ('folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='vault.category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='vault.chapter')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='vault.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='videos.pdfdocument'),
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
