# Generated by Django 4.2.27 on 2026-02-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=50)),
                ('api_hash', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('session_string', models.TextField(blank=True, default='', help_text='Telethon StringSession')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
